module.exports = {
  profile: {
    user: {
      tableName: "user_",
      key: ["user_id"],
      field: ["user_id", "email", "phone_number", "password"],
      updateItem: ["email", "phone_number", "password"],
      addItem: [],
    },
    Basic: {
      tableName: "profile_jobseeker",
      key: ["profile_id"],
      fields: [
        "profile_id",
        "full_name",
        "title",
        "job_function_id",
        "career_target",
        "city_id",
        "salary_expect",
        "year_exp",
        "gender",
        "marital_status",
        "birthday",
        "address",
        "district_id",
        "nationality_id",
        "level_id",
      ],
      updateItem: [
        "title",
        "full_name",
        "job_function_id",
        "career_target",
        "city_id",
        "salary_expect",
        "year_exp",
        "gender",
        "marital_status",
        "birthday",
        "address",
        "district_id",
        "nationality_id",
        "level_id",
      ],
      addItem: [],
    },
    skill: {
      tableName: "profile_skill",
      key: ["profile_id", "skill_id"],
      fields: ["profile_id", "skill_id"],
      updateItem: ["skill_id"],
      addItem: ["profile_id", "skill_id"],
    },
    education: {
      tableName: "profile_education",
      key: ["profile_education_id", "profile_id"],
      fields: [
        "profile_education_id",
        "profile_id",
        "education_id",
        "major",
        "school",
        "from_",
        "to_",
      ],
      updateItem: ["education_id", "major", "school", "from_", "to_"],
      addItem: [
        "profile_id",
        "education_id",
        "major",
        "school",
        "from_",
        "to_",
      ],
    },
    experience: {
      tableName: "profile_experience",
      key: ["profile_experience_id", "profile_id"],
      fields: [
        "profile_experience_id",
        "profile_id",
        "exp_title",
        "exp_from",
        "exp_to",
        "exp_company",
        "exp_description",
      ],
      updateItem: [
        "profile_id",
        "exp_title",
        "exp_from",
        "exp_to",
        "exp_company",
        "exp_description",
      ],
      addItem: [
        "profile_id",
        "exp_title",
        "exp_from",
        "exp_to",
        "exp_company",
        "exp_description",
      ],
    },
    language: {
      tableName: "profile_language",
      key: ["language_id", "profile_id"],
      fields: ["profile_id", "language_id"],
      updateItem: ["language_id"],
      addItem: ["profile_id", "language_id"],
    },
    project: {
      tableName: "profile_project",
      key: ["profile_project_id", "profile_id"],
      fields: [
        "profile_project_id",
        "profile_id",
        "project_name",
        "project_from",
        "project_to",
        "project_description",
      ],
      updateItem: [
        "project_name",
        "project_from",
        "project_to",
        "project_description",
      ],
      addItem: [
        "profile_id",
        "project_name",
        "project_from",
        "project_to",
        "project_description",
      ],
    },
    certification: {
      tableName: "profile_certification",
      key: ["profile_certifications_id", "profile_id"],
      fields: [
        "profile_certifications_id",
        "profile_id",
        "certifications",
        "month_",
      ],
      updateItem: ["certifications", "month_"],
      addItem: ["profile_id", "certifications", "month_"],
    },
    cv: {
      tableName: "profile_cv",
      key: ["cv_id", "profile_id"],
      fields: ["cv_id", "profile_id", "cv_name", "cv_link", "create_at"],
      updateItem: [],
      addItem: ["profile_id", "cv_name", "cv_link", "create_at"],
    },
  },
  logs: {
    apply_job: {
      tableName: "logs_jobseeker_apply_job",
      key: ["jobseeker_id", "job_id"],
      fields: ["jobseeker_id", "job_id", "create_at"],
      updateItem: [],
      addItem: ["jobseeker_id", "job_id", "create_at"],
    },
    save_job: {
      tableName: "logs_jobseeker_save_job",
      key: ["jobseeker_id", "job_id"],
      fields: ["jobseeker_id", "job_id", "create_at"],
      updateItem: [],
      addItem: ["jobseeker_id", "job_id", "create_at"],
    },
    follow_employer: {
      tableName: `logs_jobseeker_follow_employer`,
      key: ["jobseeker_id", "employer_id"],
      fields: ["jobseeker_id", "employer_id", "create_at"],
      updateItem: [],
      addItem: ["jobseeker_id", "employer_id", "create_at"],
    },
    view_job: {
      tableName: `logs_jobseeker_view_job`,
      key: ["jobseeker_id", "job_id"],
      fields: ["jobseeker_id", "job_id", "create_at"],
      updateItem: [],
      addItem: ["jobseeker_id", "job_id", "create_at"],
    },
  },
};
